CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR (100) UNIQUE NOT NULL,
    hashed_password VARCHAR (255) NOT NULL,
    first_name VARCHAR (50),
    last_name VARCHAR (50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);